= Objects

[plantuml]
----
@startuml

class Post {
    id: int
    title: string
    content: string
    author: string
    createdDate: Date
    category: int
    likes: int
    dislikes: int
}

class Comment {
    id: int
    content: string
    author: string
    post: int
    createdDate: Date
    likes: int
    dislikes: int
}

class Category {
    id: int
    name: string
    description: string
}

Post -- Category

Post --  Comment

@enduml
----

== Use cases

.Usecase diagramm von dem Messageboard
[plantuml]
----
@startuml

left to right direction

rectangle MessageBoard {
    usecase "Post erstellen" as UC1
    usecase "Post Kommentieren" as UC2
    usecase "Post bearbeiten" as UC3
    usecase "Post löschen" as UC4
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4

@enduml
----

=== UC1 Post erstellen

Ich will unter einem beliebigen Namen einen Post erstellen.

=== UC2 Post Kommentieren

Ich will unter einem Post unter einem beliebigen Namen einen Kommentar erstellen.

=== UC3 Post bearbeiten

Ich will den Inhalt jegliches Posts bearbeiten.

=== UC4 Post löschen

Ich will einen beliebigen Post löschen.

== UC5 Kategorie erstellen

[plantuml]
----
@startuml

actor user

user -> backend : POST /posts
user <- backend : 201 Post
@enduml
----

Vom user kann eine neue Kategorie erstellt werden.

== Test cases

=== TC1 Standardkategorien abrufen

|===
|Typ | Beschreibung

|Beschreibung
|Nach einem Restart wird getestet, welche Kategorien bereits vorhanden sind.

|Vorbedingungen
|Backend vorhanden

|Steps
|1. Backend neustarten

2. Auf den endpoint `/categories` gehen

3. Die Ergebnis vergleichen

|Ergebnis
|Die Kategorie "Rick Astley Pics" ist vorhanden
|===


=== TC2 Kategorie erstellen

|===
|Typ | Beschreibung

|Beschreibung
|Wenn eine Kategorie erstellt wird, wird dieselbe Kategorie erfolgreich zurückgegeben.

|Vorbedingungen
|Backend läuft

|Steps
|1. Kateogorie namens "C++ Q&A" mit der Beschreibung "By Bjarne Stroustrup" und der ID "0" erstellen.

2. Das Ergebnis vergleichen

|Ergebnis
| Die ID ist nicht "0", und die Beschreibung und der Name ist gleich.
|===